---
- hosts: all
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - fcitx-mozc
          - flameshot
          - xclip
        state: present
        update_cache: false


