---
- hosts: all
  tasks:
    - name: Ensure fonts directory
      file:
        path: "/usr/share/fonts/{{ item }}"
        state: directory
      with_items:
        - noto
        - HackGen
    
    # noto
    - name: Check Noto Sans exists
      stat:
        path: /usr/share/fonts/noto/NotoSansJP-Regular.otf
      register: notosans
    
    - name: Download Noto
      unarchive:
        src: "{{ item }}"
        dest: /usr/share/fonts/noto
        remote_src: yes
      with_items:
        - https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifJP.zip
        - https://noto-website-2.storage.googleapis.com/pkgs/NotoSansJP.zip
      when: not notosans.stat.exists

    # HackGen
    - name: Check HackGen exists
      stat:
        path: /usr/share/fonts/HackGen/HackGen_NF_v2.9.0
      register: hackgen

    - name: Download HackGen
      unarchive:
        src: "{{ item }}"
        dest: /usr/share/fonts/HackGen
        remote_src: yes
      with_items:
        - https://github.com/yuru7/HackGen/releases/download/v2.9.0/HackGen_NF_v2.9.0.zip
      when: not hackgen.stat.exists

    - name: Update font cache
      shell: fc-cache -vf
      changed_when: false

