---
- hosts: all
  tasks:
    - name: Install sway
      ansible.builtin.apt:
        pkg:
          - sway 
          - waybar 
          - foot 
          - wofi 
          - mako-notifier 
          - swaylock 
          - swayidle 
          - swaybg 
          - grim 
          - slurp 
          - wl-clipboard 
          - kanshi 
          - xwayland 
          - xdg-desktop-portal-wlr
          - wdisplays # for display settings
          - pulseaudio-utils # for audio control
          - wob
        state: present
        update_cache: false

