---
- hosts: all
  tasks:
    - name: Install TUI utilities
      ansible.builtin.apt:
        pkg:
          - curl
          - gawk
          - git
          - htop
          - libfontconfig1-dev # alacritty
          - libfreetype6-dev # alacritty
          - libimage-exiftool-perl
          - libxcb-xfixes0-dev # alacritty
          - make
          - neofetch
          - neovim
          - ranger
          - rclone
          - ruby
          - software-properties-common
          - tig
          - tmux
          - tree
        state: present
        update_cache: false

    - name: Install peco
      ansible.builtin.unarchive:
        src: https://github.com/peco/peco/releases/download/v0.6.0/peco_0.6.0_linux_amd64.tar.gz
        dest: /usr/local/bin
        include:
          - peco
        #extra_opts:
        #  - --strip-components=1
        remote_src: yes
        owner: root
        group: root
        mode: '0755'

    - name: Install fzf
      ansible.builtin.unarchive:
        src: https://github.com/junegunn/fzf/releases/download/v0.70.0/fzf-0.70.0-linux_amd64.tar.gz
        dest: /usr/local/bin
        include:
          - fzf
        #extra_opts:
        #  - --strip-components=1
        remote_src: yes
        owner: root
        group: root
        mode: '0755'

    - name: Remove utilities
      ansible.builtin.apt:
        name: nano
        state: absent
        update_cache: false

    - name: Install enhancd
      ansible.builtin.git:
        repo: https://github.com/b4b4r07/enhancd.git
        dest: /opt/enhancd
        update: no

    - name: Install zoxide
      ansible.builtin.unarchive:
        src: https://github.com/ajeetdsouza/zoxide/releases/download/v0.9.9/zoxide-0.9.9-x86_64-unknown-linux-musl.tar.gz
        dest: /usr/local/bin
        include:
          - zoxide
        #extra_opts:
        #  - --strip-components=1
        remote_src: yes
        owner: root
        group: root
        mode: '0755'

    - name: Copy diff-highlight
      ansible.builtin.copy:
        src: /usr/share/doc/git/contrib/diff-highlight/diff-highlight
        dest: /usr/local/bin/diff-highlight
        mode: '0755'

    - name: Install Gogh
      ansible.builtin.git:
        repo: https://github.com/anjn/Gogh.git
        dest: /opt/gogh
        update: no

