---
- hosts: all
  tasks:
    - name: Install TUI utilities
      ansible.builtin.apt:
        pkg:
          - curl
          - git
          - htop
          - libimage-exiftool-perl
          - neovim
          - peco
          - ranger
          - rclone
          - ruby
          - software-properties-common
          - tig
          - tmux
          - tree
        state: present
        update_cache: false

    - name: Remove utilities
      ansible.builtin.apt:
        name: nano
        state: absent
        update_cache: false

    - name: Install enhancd
      ansible.builtin.git:
        repo: 'https://github.com/b4b4r07/enhancd.git'
        dest: /opt/enhancd
        update: no

    - name: Copy diff-highlight
      ansible.builtin.copy:
        src: /usr/share/doc/git/contrib/diff-highlight/diff-highlight
        dest: /usr/local/bin/diff-highlight
        mode: '755'

