[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1

[[plugins]]
repo = 'SirVer/ultisnips'
on_i = 1

# [[plugins]]
# repo = 'Shougo/neosnippet'
# hook_source = '''
#   imap <C-k> <Plug>(neosnippet_expand_or_jump)
#   smap <C-k> <Plug>(neosnippet_expand_or_jump)
#   xmap <C-k> <Plug>(neosnippet_expand_target)
#   if has('conceal')
#     set conceallevel=2 concealcursor=niv
#   endif
# '''
# on_i  = 1
# on_ft = ['snippet']
# depends = ['neosnippet-snippets']

[[plugins]]
repo   = 'Shougo/unite.vim'
on_cmd = 'Unite'

[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo      = 'Shougo/neoyank.vim'
on_source = ['unite.vim']

[[plugins]]
repo      = 'h1mesuke/unite-outline'
on_source = ['unite.vim']

[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = 'toml'
