#!/usr/bin/bash
set -ex

function set_backlight {
  if [[ $1 -gt 100 ]] ; then
    xbacklight -set 100
  elif [[ $1 -lt 1 ]] ; then
    xbacklight -set 1
  else
    xbacklight -set $1
  fi
}

value=$(xbacklight -get | sed 's/\..*//')

case $1 in
  up)
    if [[ $value -ge 10 ]] ; then
      set_backlight $((value+10))
    else
      set_backlight $((value+3))
    fi
    ;;
  down)
    if [[ $value -gt 10 ]] ; then
      set_backlight $((value-10))
    else
      set_backlight $((value-3))
    fi
    ;;
  *)
    xbacklight $*;;
esac
