#!/usr/bin/env bash

case $BLOCK_BUTTON in
  4) $HOME/dotfiles/script/linux/backlight down ;;
  5) $HOME/dotfiles/script/linux/backlight up ;;
esac

value=$(xbacklight -get | sed 's/\..*//')

echo " $value%"
