#!/usr/bin/env bash

acpi=$(acpi -b)
percent=$(echo $acpi | awk -F, '{print $2}' | sed 's/%//')

status="?"
color=
case $acpi in
  *Discharging*)
    if [[ $percent -ge 80 ]] ; then
      status=""
    elif [[ $percent -ge 60 ]] ; then
      status=""
    elif [[ $percent -ge 40 ]] ; then
      status=""
      color="#FFF600"
    elif [[ $percent -ge 20 ]] ; then
      status=""
      color="#FFAE00"
    else
      status=""
      color="#FF0000"
    fi
    ;;
  *Charging*)    status="" ;;
  *Full*)        status="" ;;
  *)             status="?" ;;
esac

echo "$status $percent%"
echo "$status $percent%"
echo "$color"
