---
- hosts: all
  tasks:
    # ~/.config
    - name: Create symbolic links to config directories
      ansible.builtin.file:
        src: "{{ playbook_dir }}/files/{{ item }}"
        dest: "~/.config/{{ item }}"
        state: link
      loop:
        - tmux
        - peco

    # ~/
    - name: Create a symbolic link to files
      ansible.builtin.file:
        src: "{{ playbook_dir }}/files/{{ item }}"
        dest: "~/{{ item }}"
        state: link
      loop:
        - .gitconfig
        - .ExifTool_config
    
    # .bash_profile
    - name: Create bash_profile
      ansible.builtin.file:
        path: ~/.bash_profile
        state: touch
    
    - name: Update bash_profile for sourcing enhancd/init.sh
      ansible.builtin.blockinfile:
        path: ~/.bash_profile
        block: "source /opt/enhancd/init.sh"
    
    # .bashrc
    - name: Update bashrc
      ansible.builtin.blockinfile:
        path: ~/.bashrc
        block: "{{ lookup('ansible.builtin.file', './files/.bashrc') }}"

