- hosts: all
  tasks:
    - name: Install "atuin" Rust package
      community.general.cargo:
        name:
          - atuin
          - starship
          - alacritty

    - name: Add nightfox theme
      ansible.builtin.command: TERMINAL=gnome-terminal /opt/gogh/installs/nightfox.sh

